name: Deploy live site

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ie1-c8-1.anuhosting.net
          username: kaptea-live@kaptea.io
          password: ${{ secrets.LIVE_SITE_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: ./
          dangerous-clean-slate: true
